config/routes.rb
Rails.application.routes.draw do

  get '/', to: "coaching#ask";

  get 'answer', to: "coaching#answer"

  get 'ask', to: "coaching#ask"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def answer
    @question = params[:question]
    @coach_answer = coach_answer_enhanced(@question)

  end

  def ask
  end

  def coach_answer(your_message)
    return "" if your_message == "I am going to work right now!"
    return "Silly question, get dressed and go to work!" if your_message.split('').last == '?'
    return "I don't care, get dressed and go to work!"
  end

  def coach_answer_enhanced(your_message)
    return "" if your_message == "I am going to work right now!".upcase
    if your_message == your_message.upcase
      return "I can feel your motivation! " + coach_answer(your_message)
    else
      return coach_answer(your_message)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_controller_helper.rb
module CoachingControllerHelper
end

app/views/coaching/answer.html.erb
<div class="answer text-center">
  <h2><%= @question %></h2>
  <p>- You</p>

  <h2><%= @coach_answer %></h2>
  <p>- Your coach</p>
  <%= link_to "Ask another question",ask_path%>
</div>

app/views/coaching/ask.html.erb
<div class="ask text-center">
  <form action="/answer" method="GET">
    <label for="question">Ask your coach something?</label>
    <input type="text" name="question" class="form-control" id="question" placeholder="ask a question?">
    <input type="submit" value="submit" class="form-control btn btn-primary" id="button-only">
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>